### ISSUE TITLE
tags v3.7.1 / v4 / v4.0.0 but no release

### ISSUE THREAD

**Issue by cpanato** [golangci/golangci-lint-action#968] opened 2024-02-10 08:09 UTC
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

There are at least 3 tags in the repo but there is no release, and then dependabot is updating the repositories with those tags.

is that something planned? I noticed that it looks like automated tag creation. can someone clarify?

thanks!

### Version of golangci-lint

n/a

### Version of the GitHub Action

v3.7.1

### Workflow file

n/a

### Go version

n/a

### Code example or link to a public repository

pr examples:
https://github.com/openvex/vexctl/pull/161
https://github.com/openvex/vexctl/pull/162

**Comment by bombsimon** [comment] 2024-02-10 08:49
Duplicate of https://github.com/golangci/golangci-lint-action/discussions/967 but I don't know if we want to keep this as an issue to address or not so leaving this open for now.

**Comment by ldez** [comment] 2024-02-10 14:11
https://github.com/golangci/golangci-lint-action/releases/tag/v4.0.0

**Closed by ldez** 2024-02-10 14:11 UTC
