### ISSUE TITLE
Optionally allow for additional "--out-format" support

### ISSUE THREAD

**Issue by chainchad** [golangci/golangci-lint-action#612] opened 2022-12-02 20:39 UTC
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

I saw some issues where others were looking for similar functionality. I would like to use this action with [SonarQube's GitHub Action](https://github.com/marketplace/actions/sonarqube-scan), which requires a file uploaded for a lint report.

### Describe the solution you'd like.

I understand that `golangci-lint` can support multiple `--out-format`'s and that this action hardcodes `--out-format=github-actions` and prevents any additional `--out-format` args. However, I would like to keep the hardcoded default but then optionally override this prevention to support additional `--out-format`'s so I can generate a file for use with the SonarQube action.

### Describe alternatives you've considered.

One alternative would be to just remove the check which prevents any additional args with `--out-format`.

**Comment by ldez** [comment] 2023-06-09 11:59
duplicate of #458

**Closed by ldez** 2023-06-09 11:59 UTC
Labels: duplicate
