### ISSUE TITLE
Add support for executing golangci-lint using `go run` method

### ISSUE THREAD

**Issue by artuross** [golangci/golangci-lint-action#664] opened 2023-01-31 11:05 UTC
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

This action already supports detecting version from `go.mod` file when `version` param is not set, but the `golangci-lint` binary is still downloaded from the internet. This may be unwanted for security reasons, but also since Go is already aware of what makes up `golangci-lint` executable, I believe a better approach would be to use Go to run the binary.

### Describe the solution you'd like.

Instead of fetching binary version from the internet, it can be run as `go run github.com/golangci/golangci-lint/cmd/golangci-lint ...` which will use the version defined in Go modules.

### Describe alternatives you've considered.

- current approach with downloading binaries from the internet
- specifying custom download path

**Comment by ldez** [comment] 2023-03-20 08:45
Duplicate of #540

**Closed by ldez** 2023-03-20 08:45 UTC
