### ISSUE TITLE
[repo] typo in description

### ISSUE THREAD

**Issue by kolyshkin** [golangci/golangci-lint-action#377] opened 2021-12-01 00:23 UTC
This repo description says
```
Official GitHub action for golangci-lint from it's authors
```

It should be `its` not `it's`.

**Comment by bombsimon** [comment] 2021-12-01 07:23
Duplicate of #304 and  #202

**Closed by bombsimon** 2021-12-01 07:23 UTC

**Comment by AlekSi** [comment] 2021-12-01 08:28
Fixed now.
