### ISSUE TITLE
Not Caching

### ISSUE THREAD

**Issue by Zamiell** [golangci/golangci-lint-action#132] opened 2020-11-28 13:28 UTC
Greetings,

Thanks for the excellent tool.

I am using golangci-lint-action for the first time and my files are being linted correctly.
However, after every run, it says the following in the "Post Run actions/checkout@v2" step:

```
Post job cleanup.
Cache hit occurred on the primary key golangci-lint.cache-2656-nogomod, not saving cache.
```

Is this normal?

For reference, [this is the code](https://github.com/Zamiell/hanabi-live/blob/49b3705865fbc48f4ddc4a213bc83296fe3e6431/.github/workflows/ci.yml#L30-L44) that I am using to call golangci-lint-action.

**Comment by ldez** [comment] 2023-06-12 17:43
duplicate of  #370

**Closed by ldez** 2023-06-12 17:43 UTC
Labels: duplicate
