### ISSUE TITLE
No annotation created if cache exists

### ISSUE THREAD

**Issue by ishikawa** [golangci/golangci-lint-action#385] opened 2022-01-13 05:01 UTC
We're facing a problem that the golangci-lint-action correctly works and found some issues in the PR code, but it won't produce any annotations in the PR. After some investigation, we found that there are many "File exists" errors when decompressing its cache. It prevents GitHub Action from creating annotations to the PR. To resolve this problem, we have to opt-out caches by specifying `skip-build-cache` and `skip-pkg-cache`.

Of course, the first time there is no cache, so everything works fine.

```
2022-01-13T04:40:11.2965429Z Requested golangci-lint 'latest', using 'v1.43.0', calculation took 118ms
2022-01-13T04:40:11.2966576Z Installing golangci-lint v1.43.0...
...
2022-01-13T04:40:12.4949233Z Cache Size: ~153 MB (160100096 B)
2022-01-13T04:40:12.4974487Z [command]/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/51388359-0acc-450c-89a5-fd48615b296c/cache.tzst -P -C /home/runner/work/mywork/mywork
2022-01-13T04:40:13.1883899Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/github.com/spf13/viper@v1.10.1/util_test.go: Cannot open: File exists
2022-01-13T04:40:13.1894488Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/github.com/spf13/viper@v1.10.1/viper_go1_15.go: Cannot open: File exists
2022-01-13T04:40:13.1895338Z /usr/bin/tar: ../../../go/pkg/mod/github.com/spf13/viper@v1.10.1/.gitignore: Cannot open: File exists
2022-01-13T04:40:13.1895930Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/github.com/spf13/viper@v1.10.1/viper_go1_16.go: Cannot open: File exists
2022-01-13T04:40:13.1896876Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/github.com/spf13/viper@v1.10.1/internal/testutil/filepath.go: Cannot open: File exists
2022-01-13T04:40:13.1897722Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/github.com/spf13/viper@v1.10.1/internal/testutil/env_go1_16.go: Cannot open: File exists
2022-01-13T04:40:13.1898515Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/github.com/spf13/viper@v1.10.1/internal/testutil/env_go1_17.go: Cannot open: File exists
...
```

Our workflow settings:

```yaml
- name: lint
  uses: golangci/golangci-lint-action@v2
  with:
    version: latest
```

**Comment by joaocostamm** [comment] 2022-05-11 09:36
Same issue for me

**Comment by FelipeLema** [comment] 2022-07-08 19:52
may be related to https://github.com/golangci/golangci-lint-action/issues/496

**Comment by lucacome** [comment] 2022-11-17 01:24
I'm seeing something similar, as in that we don't get annotations
```
...
  Error: /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220909003341-f21342109be1/stackoverflow/stackoverflow.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220909003341-f21342109be1/vk/vk.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220909003341-f21342109be1/oauth2.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220909003341-f21342109be1/fitbit/fitbit.go: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220909003341-f21342109be1/CONTRIBUTING.md: Cannot open: File exists
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Failed to restore: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
  Cache not found for input keys: golangci-lint.cache-2758-0bc2bb025ceba06555192588e80c455eb31482c8, golangci-lint.cache-2758-
  Prepared env in 6239ms
```
but at the end it says `Cache not found` 🤔

**Comment by bschaatsbergen** [comment] 2023-12-05 00:54
Interesting that this isn't fixed yet, I'm simply copying the workflow file recommended to use in the README and the annotations are not being created.

**Comment by ldez** [comment] 2024-05-04 16:22
Duplicate of #135

**Closed by ldez** 2024-05-04 16:22 UTC
Labels: duplicate, area: cache
