### ISSUE TITLE
Specify golangci-lint executable in the action 

### ISSUE THREAD

**Issue by yaxiong-zhao** [golangci/golangci-lint-action#631] opened 2022-12-24 05:35 UTC
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

The current action download golangci-lint executable

github action cache usually make that fast

I'd like to have the ability to specify custome path to the golangci-lint
for example, if action runs inside a container, include golangci-lint in the container's path

### Describe the solution you'd like.

Provide an option to specify a path in the action runtime filesystem.

### Describe alternatives you've considered.

No alternative I can think of

**Comment by atzoum** [comment] 2023-01-07 13:46
👍 this would also allow for using custom golangci-lint binaries, containing private linters which is now not possible

**Comment by ldez** [comment] 2023-02-08 09:43
duplicate of #540

**Closed by ldez** 2023-02-08 09:43 UTC
Labels: enhancement
