### ISSUE TITLE
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/gorilla/css@v1.0.0/scanner/doc.go: Cannot open: File exists

### ISSUE THREAD

**Issue by raliqala** [golangci/golangci-lint-action#387] opened 2022-01-18 16:08 UTC
Hello Good Day  

Am trying to run golangci-lint-action but i'm receiving this error

```
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/nested_0.txt.html: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/html.txt: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/nested_2.txt.html: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/adjacent.txt: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/hello_world.txt: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/nested_0.txt: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/adjacent.txt.html: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/testdata/nested_2.txt: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/benchmark.txt: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/Makefile: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/LICENSE: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/annotate_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/sourcegraph/annotate@v0.0.0-20160123013949-f4cad6c6324d/annotate.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/bytebuffer_timing_test.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/.travis.yml: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/README.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/doc.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/bytebuffer_example_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/pool.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/bytebuffer.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/LICENSE: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/pool_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/bytebuffer_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/server_example_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/server_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/bytesconv_table_gen.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/stream_timing_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/bytesconv_64.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/header.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/brotli_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/lbclient.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/workerpool_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/peripconn.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/uri_unix.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/args_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/bytesconv_table.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/header_regression_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/workerpool.go: Cannot open: File exists
```

![image](https://user-images.githubusercontent.com/30502407/149973689-7a15b47f-1bac-417d-a19a-a3d691478d28.png)

Please help.

This is my .yml file

```
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - dev
      - main
  pull_request:
permissions:
  contents: read

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        # os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        os: ["ubuntu-latest"]
        go: ["1.17.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go }}
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
    - uses: dominikh/staticcheck-action@v1.0.0
      with:
        version: "2021.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}
    
```

**Comment by bombsimon** [comment] 2022-01-18 16:26
Duplicate of #244

**Closed by bombsimon** 2022-01-18 16:26 UTC
