### ISSUE TITLE
Run golangcl-lint in all go modules in repository

### ISSUE THREAD

**Issue by robert-zaremba** [golangci/golangci-lint-action#544] opened 2022-08-08 16:50 UTC
Locally I'm running the following command to lint all go modules in the repository:

```
find -name go.mod -execdir go run github.com/golangci/golangci-lint/cmd/golangci-lint run --timeout=5m \;
```

Can we add a support for that in `golancl-lint`? It's not dev-friendly to manually add a step and manually assign working directory for every module.

**Comment by torkelrogstad** [comment] 2022-11-10 15:29
If you're using Go workspaces, this works better. Assuming you have three modules `foo`, `bar` and `qux`, you can do `golangci-lint run ./foo./... ./bar/... ./qux/...`, or also ` golangci-lint run $(go list -m  | awk 'NF{print $$0 "/..."}')`

**Comment by n-event** [comment] 2022-12-01 12:20
@torkelrogstad, in go1.18, if we have a workspace with multiple modules defined in go.work file, how should we run the action to leverage Github pull request comments by the action?
Specifically, I want to run the command given below and report the issues in pull requests:
```bash
golangci-lint run --out-format=github-actions -- \                                                                                                     
            $(go work edit -json | jq -c -r '[.Use[].DiskPath | map_values(. + "/...")| join(" ")')
```

**Comment by weberc2** [comment] 2024-04-24 12:58
Yeah, this is causing me some pain too. Our repo has an arbitrary number of fine-grained Go modules, and it's painful to have to keep this action invocation in sync as modules are added, renamed, and deleted from our repository.

**Comment by ldez** [comment] 2024-05-01 03:30
duplicate of #74

**Closed by ldez** 2024-05-01 03:30 UTC
Labels: question
