### ISSUE TITLE
Support custom plugins

### ISSUE THREAD

**Issue by connorszczepaniak-wk** [golangci/golangci-lint-action#690] opened 2023-03-01 14:38 UTC
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

I'd like to be able to use custom golangci-lint plugins with the GitHub action. I can _almost_ achieve this with the following steps:
- Build a docker container with a pre-built golangci-lint
- Also build my custom plugins and put them in this docker container
- Use this container in the GitHub action with `container: my-golangci-container`
- Missing capability: tell the action to skip downloading the asset and point to the pre-installed version on my container instead

Since plugins need to be built from the same `go.mod` that the tool itself is built from, I need a way to point the action to my binary.

### Describe the solution you'd like.

#676 Is achieving something similar, but for this use-case it can be even simpler: if I can specify the path to `golangci-lint` on the running container and tell the action to skip downloading the asset (and just use the one I'm pointing to instead), everything would work well.

### Describe alternatives you've considered.

I can currently run `golangci-lint` as a separate action on my own container, but then I miss out on getting comments on my PR, caching, etc.

**Comment by ldez** [comment] 2023-03-20 08:44
Feels like a duplicate of #631

**Comment by connorszczepaniak-wk** [comment] 2023-04-04 03:00
@ldez yes, it seems like it. I see there is a bit of a chain of duplicates, ending with #540. These issues are closed, but I don't see a PR referencing them. Maybe I missed it -- is this already supported?

**Comment by ldez** [comment] 2023-06-06 23:37
I think an idea can be to be able to build golangci-lint (through `go install` see #540 with `CGO_ENABLED=1`) and add an extra configuration for plugins.

The `with` of GitHub Action only supports first-level key-value then it's not the right solution for the extra configuration.
```yml
with:
  foo: bar
```

Then maybe the extra configuration can be provided via a dedicated file, something like that:
```yml
plugins:
  - path: /path/to/plugin/sources/
    destination: ./example/foo.so
  - path: /path/to/another/plugin/sources/
    destination: ./example/bar.so
```

related to https://github.com/golangci/golangci-lint/issues/2566

FYI #540 is not closed.

**Closed** 2023-06-12 17:16 UTC
Labels: enhancement
