### ISSUE TITLE
Ability to make suggested changes on a PR

### ISSUE THREAD

**Issue by szunami** [golangci/golangci-lint-action#35] opened 2020-07-10 17:55 UTC
Really appreciating this action, and it's ability to annotate PRs.

For many of the lint / vet rules, I think there are somewhat straightforward fixes. It would be awesome if this action could make suggested changes when possible (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request). Is this at all feasible?

**Comment by sayboras** [comment] 2020-07-10 23:09
Once #5 is tackled, we can do this one. As suggesttion changes based on my understanding is just comment with ```suggestion ``` block

**Comment by sayboras** [comment] 2020-07-12 12:53
Just a note on this that not all linters are giving `suggestion` to correct error.

**Comment by szunami** [comment] 2020-07-12 15:14
That makes sense.

I think the `suggestion` UX is such a paradigm shift that could really improve adoption of linters, and would love to see those that don't currently support it think about what they could do (understanding that there are technical limitations). Thanks for the response, I might have some time to contribute in the near future. Please keep me posted!

**Comment by ldez** [comment] 2024-05-09 14:41
Kind of a duplicate of #5

The review comments are just comments with position.

**Closed by ldez** 2024-05-09 14:41 UTC
Labels: duplicate, enhancement
