### ISSUE TITLE
Typo in repo description (`it's` → `its`)

### ISSUE THREAD

**Issue by Horgix** [golangci/golangci-lint-action#304] opened 2021-08-03 18:12 UTC
Hello there  :wave: 

Currently, this is the description of this repository:

> Official GitHub action for golangci-lint from it's authors 

![screenshot_2021-08-03-195923_285x93_selection](https://user-images.githubusercontent.com/4584397/128063664-3d18cde8-fa78-4a0f-903a-8686d1af8cd7.png)

I _think_ that it should be `its` (the possessive pronoun) and not `it's` (contraction of `it is`). I'd gladly open a PR to fix it but since it's the repo metadata I can't so here is a small issue about it :slightly_smiling_face:

**Comment by bombsimon** [comment] 2021-08-04 14:42
Duplicate of #202

**Closed by bombsimon** 2021-08-04 14:42 UTC
